'use client'
import { TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Tabs } from "@radix-ui/react-tabs"
import { useQuery } from "@tanstack/react-query"
import axios from "axios"
import { useRouter } from "next/navigation"
import { PageWrapper } from "../page-wrapper"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
 type CategoriesType ={
    id:string,
    name:string
 }
 export default function CategoriesLayout({
    children,
 }:{
    children:React.ReactNode
 }) {
    const route = useRouter()
    const{data:categoryResults, isLoading}=useQuery<CategoriesType[]>({
        queryFn:async ()=>{
            const{data} = await axios.get("http://localhost:3000/categories")
            return data
        },
        queryKey:['categories-query'],
    })
    console.log(categoryResults)

    return(
        <PageWrapper>
        <div className="p-5">
            <Tabs>
                <TabsList className="w-[300px] mb-3">
                    {categoryResults?.map((category) => (
                        <TabsTrigger key={category.id} className="w-[150px] capitalize" value={category.id} onClick={() => route.push(`/categories/${category.name}`)}>{category.name}</TabsTrigger>
                    ))}

                </TabsList>
                {children}
            </Tabs>

        </div>
        </PageWrapper>
    )
 }