export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }
  
  export default function DesignationLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return(
      <>
      {children}
      </>
    )
  }